services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: c_portainer
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

  jenkins:
    build: ./jenkins   // Burada hangi klasörde ise ona göre güncellenecektir.
    container_name: c_jenkins_docker
    restart: always
    privileged: true
    environment:
      DOCKER_HOST: tcp://docker:2376
      DOCKER_CERT_PATH: /certs/client
      DOCKER_TLS_VERIFY: '1'
    ports:
      - "8000:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - jenkins-docker-certs:/certs/client

volumes:
  jenkins_home:
  portainer_data:
