services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: c_portainer
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

  jenkins:
    build: .
    container_name: c_jenkins_docker
    restart: always
    privileged: true
    environment:         # Burası hata verebiliyor. environment maddesini silebilirsin.
      DOCKER_HOST: tcp://docker:2376
      DOCKER_CERT_PATH: /certs/client
      DOCKER_TLS_VERIFY: '1'
    ports:
      - "8000:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - jenkins-docker-certs:/certs/client

volumes:
  jenkins_home:
  portainer_data:
  jenkins-docker-certs:
#NOT: Eğer şu hatayı alırsak : 
# ERROR: permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get "http://%2Fvar%2Frun%2Fdocker.sock/v1.45/info": dial unix /var/run/docker.sock: connect: permission denied
# Docker ait /var/run/docker.sock yetkilerini Jenkins tarafından yazılabilir yetkisi vermelisin.
